# Generated by Django 2.2.5 on 2019-11-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_remover_sponsorship")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.CharField(
                default="slug",
                help_text="A unique, readable identifier",
                max_length=255,
                unique=True,
            ),
        )
    ]
