# Generated by Django 2.2.5 on 2019-11-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_eventregistrationtype_event")]

    operations = [
        migrations.RemoveField(model_name="eventregistration", name="event"),
        migrations.AddField(
            model_name="eventregistration",
            name="registration_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="core.EventRegistrationType",
            ),
        ),
    ]
