# Generated by Django 2.2.7 on 2019-11-13 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0008_auto_20191108_1819")]

    operations = [
        migrations.AlterField(
            model_name="eventownership",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ownerships",
                to="core.Event",
            ),
        ),
        migrations.AlterField(
            model_name="eventownership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_ownerships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
