---

version: '3'

services:
  web:
    image: nginx:1
    command: "sh -c 'apt update && DEBIAN_FRONTEND=noninteractive apt install ssl-cert && exec nginx -g \"daemon off;\"'"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - media:/tmp/media
      - static:/tmp/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    environment:
      API_URL: http://backend:8000/
      EVENTOS2_FRONTEND_FORCE_SLUG: test
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DATABASE_URL: 'postgres://eventos2:eventos2@db:5432/eventos2'
      ALLOWED_HOSTS: backend,localhost
    volumes:
      - media:/tmp/media
      - static:/tmp/static
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: eventos2
      POSTGRES_PASSWORD: eventos2
      POSTGRES_DB: eventos2
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  media:
  static:
