from eventos2.core.serializers.activity import *
from eventos2.core.serializers.activity_registration import *
from eventos2.core.serializers.event import *
from eventos2.core.serializers.event_registration import *
from eventos2.core.serializers.review import *
from eventos2.core.serializers.review_answer import *
from eventos2.core.serializers.review_request import *
from eventos2.core.serializers.submission import *
from eventos2.core.serializers.submission_document import *
from eventos2.core.serializers.track import *
from eventos2.core.serializers.track_review_question import *
from eventos2.core.serializers.track_submission_document_slot import *
from eventos2.core.serializers.user import *
