# Generated by Django 2.2.5 on 2019-10-11 15:08

import secrets

from django.db import migrations, models

import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_key",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        help_text="Used to attach the image to another object. Cannot be used to retrieve the image file.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        help_text="Used to retrieve the image itself. Should not be readable until the image is attached to another object.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("file", models.ImageField(upload_to=images.models.image_file_path)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
