from eventos2.core.views.activity import *
from eventos2.core.views.activity_registration import *
from eventos2.core.views.event import *
from eventos2.core.views.event_registration import *
from eventos2.core.views.review import *
from eventos2.core.views.review_request import *
from eventos2.core.views.submission import *
from eventos2.core.views.submission_document import *
from eventos2.core.views.track import *
from eventos2.core.views.track_review_question import *
from eventos2.core.views.track_submission_document_slot import *
from eventos2.core.views.user import *
