# Generated by Django 2.2.5 on 2019-11-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0002_unique_email")]

    operations = [
        migrations.RemoveField(model_name="event", name="location"),
        migrations.DeleteModel(name="Sponsorship"),
        migrations.DeleteModel(name="SponsorshipCategory"),
    ]
