# Generated by Django 2.2.5 on 2019-11-07 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_stuff")]

    operations = [
        migrations.AddField(
            model_name="eventregistrationtype",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_types",
                to="core.Event",
            ),
        )
    ]
