# Generated by Django 2.2.5 on 2019-11-08 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0007_registration_fix_relation")]

    operations = [
        migrations.AddField(
            model_name="eventregistrationtype",
            name="registrations",
            field=models.ManyToManyField(
                related_name="event_registrations",
                through="core.EventRegistration",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="registration_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.EventRegistrationType",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
