# Generated by Django 3.0.4 on 2020-05-01 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20191113_1840"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventregistration",
            name="registration_type",
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="event",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.Event",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="EventRegistrationType",
        ),
    ]
