# Generated by Django 3.0.4 on 2020-05-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remote_eventregistrationtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="event",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="core.Event",
            ),
            preserve_default=False,
        ),
    ]
