# Generated by Django 3.0.7 on 2020-06-23 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_activity_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(
                help_text="The activity's name in its native language", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="name_english",
            field=models.CharField(
                blank=True, help_text="The activity's name in english", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="activityownership",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ownerships",
                to="core.Activity",
            ),
        ),
        migrations.AlterField(
            model_name="activityownership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_ownerships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="core.Event",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
