# Generated by Django 3.0.7 on 2020-07-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_tracks_submissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="ends_on",
        ),
        migrations.RemoveField(
            model_name="track",
            name="starts_on",
        ),
    ]
