# Generated by Django 3.0.7 on 2020-07-09 20:48

import secrets

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_track_remove_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.CharField(
                default=secrets.token_urlsafe,
                help_text="Random sequence to be used as a public identifier.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
