# Generated by Django 3.0.7 on 2020-07-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_extra_permissions"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_event_registration"
            ),
        ),
        migrations.AddConstraint(
            model_name="activityregistration",
            constraint=models.UniqueConstraint(
                fields=("activity", "event_registration"),
                name="unique_activity_registration",
            ),
        ),
    ]
