# Generated by Django 3.0.8 on 2020-07-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_unique_registrations"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackSubmissionDocumentSlot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The slot's name in its native language",
                        max_length=255,
                    ),
                ),
                (
                    "name_english",
                    models.CharField(
                        blank=True,
                        help_text="The slot's name in english",
                        max_length=255,
                    ),
                ),
                ("starts_on", models.DateTimeField()),
                ("ends_on", models.DateTimeField()),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission_document_slots",
                        to="core.Track",
                    ),
                ),
            ],
        ),
    ]
