# Generated by Django 3.0.8 on 2020-07-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("core", "0018_tracksubmissiondocumentslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="media.Document",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.TrackSubmissionDocumentSlot",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.Submission",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="submissiondocument",
            constraint=models.UniqueConstraint(
                fields=("slot", "submission"), name="unique_submission_document"
            ),
        ),
    ]
