# Generated by Django 3.0.8 on 2020-07-23 19:01

import datetime

import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_submissiondocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="ends_on",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="track",
            name="starts_on",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
