# Generated by Django 3.0.8 on 2020-07-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20200723_1901"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "permissions": [
                    (
                        "register_self_into_activity",
                        "Can self-register into an activity",
                    ),
                    (
                        "view_registrations_for_activity",
                        "Can view registrations for an activity",
                    ),
                ]
            },
        ),
    ]
