# Generated by Django 3.0.6 on 2020-10-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_activity_track_slugs"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackReviewQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("yes_no", "Yes No"),
                            ("grade_zero_to_ten", "Grade Zero To Ten"),
                            ("text", "Text"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_questions",
                        to="core.Track",
                    ),
                ),
            ],
        ),
    ]
