# Generated by Django 3.0.6 on 2020-10-16 17:16

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_auto_20201013_1851"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={
                "permissions": [
                    ("add_review_to_submission", "Can add a review to a submission")
                ]
            },
        ),
        UnaccentExtension(),
    ]
