# Generated by Django 3.0.6 on 2020-10-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_auto_20201016_1716"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "permissions": [
                    (
                        "view_registrations_for_event",
                        "Can view registrations for an event",
                    ),
                    ("view_activities_for_event", "Can view activities for an event"),
                    ("view_tracks_for_event", "Can view tracks for an event"),
                    ("view_submissions_for_event", "Can view submissions for an event"),
                    (
                        "view_activity_registrations_for_event",
                        "Can view activity registrations for an event",
                    ),
                    ("register_self_into_event", "Can self-register into an event"),
                ]
            },
        ),
    ]
