# Generated by Django 2.2.5 on 2019-09-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The event's name in its native language",
                        max_length=255,
                    ),
                ),
                (
                    "name_english",
                    models.CharField(
                        blank=True,
                        help_text="The event's name in english",
                        max_length=255,
                    ),
                ),
                ("starts_on", models.DateTimeField()),
                ("ends_on", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        help_text="Where the event will take place", max_length=255
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SponsorshipCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsor",
                    models.CharField(
                        help_text="The individual or organization who is sponsoring the event",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.SponsorshipCategory",
                    ),
                ),
                (
                    "sponsored_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorships",
                        related_query_name="sponsorship",
                        to="core.Event",
                    ),
                ),
            ],
        ),
    ]
