# Generated by Django 2.2.5 on 2019-10-11 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("images", "0001_initial"), ("core", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="images.Image",
            ),
        )
    ]
