# Generated by Django 2.2.5 on 2019-10-10 18:40

import secrets

from django.db import migrations, models

import core.models.image


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        help_text="User-facing identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.ImageField(upload_to=core.models.image.image_file_path),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
